import type { ContactConversation } from './typings'

export const MOCK_CONVERSATIONS: ContactConversation[] = [
  // ─── Sarah Chen · Apex Technologies ───────────────────────────────────────
  {
    thread: {
      id: 'c1',
      contactName: 'Sarah Chen',
      contactInitials: 'SC',
      avatarColor: 'bg-blue-500',
      contactCompany: 'Apex Technologies',
      lastMessage: 'Can we push the demo to Thursday?',
      lastMessageTime: '10:42 AM',
      lastChannel: 'email',
      unreadCount: 2,
      status: 'open',
    },
    emails: [
      {
        id: 'e1-1',
        from: 'sarah.chen@apextech.io',
        to: 'you@company.com',
        subject: 'Interested in your CRM platform',
        body: "Hi,\n\nI came across your CRM platform and would love to learn more. We're a 50-person SaaS company currently struggling with lead tracking across our sales team.\n\nWould it be possible to schedule a short call this week?\n\nThanks,\nSarah Chen\nHead of Sales, Apex Technologies",
        timestamp: '2026-02-20 09:14 AM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e1-2',
        from: 'you@company.com',
        to: 'sarah.chen@apextech.io',
        subject: 'Re: Interested in your CRM platform',
        body: "Hi Sarah,\n\nGreat to hear from you! We'd love to walk you through the platform.\n\nI've blocked out Wednesday at 2 PM or Thursday at 10 AM — which works better for you? I'll send a calendar invite once confirmed.\n\nLooking forward to connecting,\nAlex",
        timestamp: '2026-02-20 11:30 AM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e1-3',
        from: 'sarah.chen@apextech.io',
        to: 'you@company.com',
        subject: 'Re: Interested in your CRM platform',
        body: "Hi Alex,\n\nThursday at 10 AM works perfectly. Could you also send over any case studies for SaaS companies similar to ours beforehand? That would help me prepare some questions.\n\nThanks,\nSarah",
        timestamp: '2026-02-21 08:55 AM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e1-4',
        from: 'sarah.chen@apextech.io',
        to: 'you@company.com',
        subject: 'Re: Demo Thursday',
        body: "Hi Alex,\n\nSomething came up on our end — can we push the demo to Thursday next week instead? Same time works for me.\n\nSorry for the short notice.\n\nSarah",
        timestamp: '2026-02-27 10:42 AM',
        direction: 'inbound',
        read: false,
      },
    ],
    sms: [
      {
        id: 's1-1',
        body: 'Hi Sarah, just confirming our demo for Thursday 10 AM. Talk soon!',
        timestamp: '2026-02-24 09:00 AM',
        direction: 'outbound',
      },
      {
        id: 's1-2',
        body: 'Thanks! Looking forward to it. Will send an agenda shortly.',
        timestamp: '2026-02-24 09:18 AM',
        direction: 'inbound',
      },
      {
        id: 's1-3',
        body: 'Hey, just emailed you about rescheduling — heads up!',
        timestamp: '2026-02-27 10:45 AM',
        direction: 'inbound',
      },
    ],
    calls: [
      {
        id: 'ca1-1',
        direction: 'outbound',
        duration: '14m 22s',
        outcome: 'answered',
        notes: 'Initial discovery call. Sarah confirmed 3 pain points: no pipeline visibility, manual reporting, and weak lead assignment. Very interested. Decision timeline is Q2.',
        timestamp: '2026-02-22 10:05 AM',
        hasRecording: true,
      },
      {
        id: 'ca1-2',
        direction: 'outbound',
        duration: '0m 0s',
        outcome: 'no-answer',
        notes: 'Called to confirm demo — no answer. Sent SMS follow-up.',
        timestamp: '2026-02-26 03:15 PM',
        hasRecording: false,
      },
    ],
    notes: [
      {
        id: 'n1-1',
        body: '@James — Sarah is a strong prospect. She mentioned their current CRM is Pipedrive but they hate the reporting. Make sure the demo highlights our custom dashboards. Budget is confirmed at ~$12k/yr.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-22 11:00 AM',
      },
    ],
  },

  // ─── Marcus Johnson · BlueStar Retail ─────────────────────────────────────
  {
    thread: {
      id: 'c2',
      contactName: 'Marcus Johnson',
      contactInitials: 'MJ',
      avatarColor: 'bg-violet-500',
      contactCompany: 'BlueStar Retail',
      lastMessage: 'Sounds good, talk soon.',
      lastMessageTime: 'Yesterday',
      lastChannel: 'sms',
      unreadCount: 0,
      status: 'pending',
    },
    emails: [
      {
        id: 'e2-1',
        from: 'you@company.com',
        to: 'm.johnson@bluestar.com',
        subject: 'CRM solution for your retail operations',
        body: "Hi Marcus,\n\nI noticed BlueStar Retail recently expanded to 12 locations — congratulations! Growing retail teams often hit friction with fragmented customer data.\n\nOur CRM has helped similar retailers centralise customer history, automate follow-ups, and increase repeat purchase rates by 18% on average.\n\nWould a 20-minute call be worthwhile this week?\n\nBest,\nAlex",
        timestamp: '2026-02-18 10:00 AM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e2-2',
        from: 'm.johnson@bluestar.com',
        to: 'you@company.com',
        subject: 'Re: CRM solution for your retail operations',
        body: "Hey Alex,\n\nThanks for reaching out. We are actually evaluating CRMs right now. Let's connect — I'm pretty busy this week but I'm free next Monday afternoon.\n\nMarcus",
        timestamp: '2026-02-19 02:20 PM',
        direction: 'inbound',
        read: true,
      },
    ],
    sms: [
      {
        id: 's2-1',
        body: 'Hey Marcus, Alex here from CRM Tool. Following up on my email — are you free for a quick chat this week?',
        timestamp: '2026-02-20 11:00 AM',
        direction: 'outbound',
      },
      {
        id: 's2-2',
        body: 'Hey Alex! Yeah let\'s do Monday. Text me the call link.',
        timestamp: '2026-02-20 11:34 AM',
        direction: 'inbound',
      },
      {
        id: 's2-3',
        body: 'Monday March 3 at 2 PM works? I\'ll send the calendar invite now.',
        timestamp: '2026-02-20 11:36 AM',
        direction: 'outbound',
      },
      {
        id: 's2-4',
        body: 'Perfect.',
        timestamp: '2026-02-20 11:40 AM',
        direction: 'inbound',
      },
      {
        id: 's2-5',
        body: 'Great, sent! Looking forward to Monday. Talk soon.',
        timestamp: '2026-02-26 09:00 AM',
        direction: 'outbound',
      },
    ],
    calls: [
      {
        id: 'ca2-1',
        direction: 'outbound',
        duration: '4m 08s',
        outcome: 'answered',
        notes: 'Brief intro call. Marcus is the decision maker. Evaluating 3 vendors. Meeting booked for Monday demo.',
        timestamp: '2026-02-21 03:00 PM',
        hasRecording: false,
      },
    ],
    notes: [
      {
        id: 'n2-1',
        body: 'Marcus is the VP of Operations — he makes the final call on software purchases. He mentioned they tried Salesforce 2 years ago and found it too complex. Keep the pitch simple and ROI-focused.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-21 03:15 PM',
      },
      {
        id: 'n2-2',
        body: '@Sarah confirm the Monday demo slot is locked in on our end. Marcus is expecting a call at 2 PM.',
        author: 'James Obi',
        authorInitials: 'JO',
        timestamp: '2026-02-24 10:00 AM',
      },
    ],
  },

  // ─── Priya Patel · Cloudify Inc. ──────────────────────────────────────────
  {
    thread: {
      id: 'c3',
      contactName: 'Priya Patel',
      contactInitials: 'PP',
      avatarColor: 'bg-emerald-500',
      contactCompany: 'Cloudify Inc.',
      lastMessage: 'Can we extend the trial by two weeks?',
      lastMessageTime: 'Feb 25',
      lastChannel: 'email',
      unreadCount: 1,
      status: 'open',
    },
    emails: [
      {
        id: 'e3-1',
        from: 'priya@cloudify.io',
        to: 'you@company.com',
        subject: 'Question about the Pro plan pricing',
        body: "Hi,\n\nWe've been on the trial for 10 days and the team really likes it. I wanted to ask about the Pro plan — does the $49/user/month price include API access, or is that add-on?\n\nAlso, do you offer annual billing with a discount?\n\nPriya Patel\nCTO, Cloudify Inc.",
        timestamp: '2026-02-17 01:45 PM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e3-2',
        from: 'you@company.com',
        to: 'priya@cloudify.io',
        subject: 'Re: Question about the Pro plan pricing',
        body: "Hi Priya,\n\nGreat news — API access is included in the Pro plan at no extra charge. And yes, annual billing gives you a 20% discount, bringing it to $39.20/user/month.\n\nWith 10 users on annual Pro, you'd be looking at ~$4,700/year.\n\nI'd love to jump on a call to walk through the API docs and answer any technical questions for your team. Are you free Thursday?\n\nBest,\nAlex",
        timestamp: '2026-02-17 04:10 PM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e3-3',
        from: 'priya@cloudify.io',
        to: 'you@company.com',
        subject: 'Trial extension request',
        body: "Hi Alex,\n\nWe're still evaluating — our dev team needs more time to test the API integrations. Can we extend the trial by two weeks? We're very close to a decision, I just don't want to rush the technical review.\n\nThanks,\nPriya",
        timestamp: '2026-02-25 11:20 AM',
        direction: 'inbound',
        read: false,
      },
    ],
    sms: [
      {
        id: 's3-1',
        body: 'Hi Priya, just checking — did you get a chance to look at the API docs I sent over?',
        timestamp: '2026-02-22 10:00 AM',
        direction: 'outbound',
      },
      {
        id: 's3-2',
        body: 'Yes! Our dev lead is reviewing them now. Will get back to you by end of week.',
        timestamp: '2026-02-22 10:45 AM',
        direction: 'inbound',
      },
    ],
    calls: [
      {
        id: 'ca3-1',
        direction: 'inbound',
        duration: '22m 10s',
        outcome: 'answered',
        notes: 'Priya called with API integration questions. Walked through webhook setup and data export endpoints. Their dev lead (Rohan) was also on the call. Positive signals — they want to automate lead ingestion from their app.',
        timestamp: '2026-02-19 02:30 PM',
        hasRecording: true,
      },
      {
        id: 'ca3-2',
        direction: 'outbound',
        duration: '0m 0s',
        outcome: 'voicemail',
        notes: 'Left a voicemail asking about trial experience. Asked her to reply by email or SMS.',
        timestamp: '2026-02-24 11:00 AM',
        hasRecording: false,
      },
      {
        id: 'ca3-3',
        direction: 'outbound',
        duration: '8m 55s',
        outcome: 'answered',
        notes: 'Discussed pricing structure and annual billing in detail. Priya confirmed team size is 10-12 users. Decision expected within 3 weeks.',
        timestamp: '2026-02-25 03:00 PM',
        hasRecording: true,
      },
    ],
    notes: [
      {
        id: 'n3-1',
        body: 'Priya is technically strong — CTO background. Make sure all technical claims are backed up. Their dev stack is Node.js + Postgres. @James can you get the webhook documentation updated before their trial ends?',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-19 03:00 PM',
      },
    ],
  },

  // ─── Tom Weber · DataSync Corp. ───────────────────────────────────────────
  {
    thread: {
      id: 'c4',
      contactName: 'Tom Weber',
      contactInitials: 'TW',
      avatarColor: 'bg-amber-500',
      contactCompany: 'DataSync Corp.',
      lastMessage: 'Contract signed. Looking forward to onboarding.',
      lastMessageTime: 'Feb 20',
      lastChannel: 'call',
      unreadCount: 0,
      status: 'resolved',
    },
    emails: [
      {
        id: 'e4-1',
        from: 'you@company.com',
        to: 'tom.weber@datasync.com',
        subject: 'Your CRM onboarding is confirmed',
        body: "Hi Tom,\n\nWelcome aboard! Your Business plan is now active.\n\nI've attached the onboarding guide and your account credentials. Our customer success team will reach out within 24 hours to schedule your kickoff call.\n\nIf you need anything in the meantime, reply here or call me directly.\n\nAlex",
        timestamp: '2026-02-20 09:00 AM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e4-2',
        from: 'tom.weber@datasync.com',
        to: 'you@company.com',
        subject: 'Re: Your CRM onboarding is confirmed',
        body: "Thanks Alex! Contract signed and looking forward to getting started. The team is excited.\n\nTom",
        timestamp: '2026-02-20 09:45 AM',
        direction: 'inbound',
        read: true,
      },
    ],
    sms: [],
    calls: [
      {
        id: 'ca4-1',
        direction: 'outbound',
        duration: '6m 40s',
        outcome: 'answered',
        notes: 'Cold call. Tom was receptive. Runs a 25-person data analytics firm. Key need: pipeline visibility for his sales team of 4. Agreed to a demo next week.',
        timestamp: '2026-02-10 02:00 PM',
        hasRecording: false,
      },
      {
        id: 'ca4-2',
        direction: 'outbound',
        duration: '38m 15s',
        outcome: 'answered',
        notes: 'Full product demo. Tom and two team members attended. Covered pipeline, reports, and task automation. Very positive. Asked for proposal with Business plan pricing.',
        timestamp: '2026-02-14 11:00 AM',
        hasRecording: true,
      },
      {
        id: 'ca4-3',
        direction: 'inbound',
        duration: '12m 00s',
        outcome: 'answered',
        notes: 'Tom called with contract questions — mainly about data export rights and SLA. Clarified both. He said he\'ll sign by end of week.',
        timestamp: '2026-02-18 04:00 PM',
        hasRecording: false,
      },
      {
        id: 'ca4-4',
        direction: 'outbound',
        duration: '5m 30s',
        outcome: 'answered',
        notes: 'Confirmed contract receipt and onboarding schedule. Deal is closed.',
        timestamp: '2026-02-20 08:30 AM',
        hasRecording: false,
      },
    ],
    notes: [
      {
        id: 'n4-1',
        body: 'Tom is a fast decision maker — went from first call to close in 10 days. Key win factors: clean UI, fast onboarding, and competitive pricing vs Hubspot. Good reference customer candidate.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-20 10:00 AM',
      },
      {
        id: 'n4-2',
        body: '@Sarah add Tom Weber to the customer reference list. He mentioned he\'d be willing to do a case study call.',
        author: 'James Obi',
        authorInitials: 'JO',
        timestamp: '2026-02-21 09:00 AM',
      },
    ],
  },

  // ─── James Okafor · GreenLeaf Ventures ────────────────────────────────────
  {
    thread: {
      id: 'c5',
      contactName: 'James Okafor',
      contactInitials: 'JO',
      avatarColor: 'bg-rose-500',
      contactCompany: 'GreenLeaf Ventures',
      lastMessage: 'I need a breakdown of the Enterprise plan features.',
      lastMessageTime: '9:15 AM',
      lastChannel: 'email',
      unreadCount: 3,
      status: 'open',
    },
    emails: [
      {
        id: 'e5-1',
        from: 'james.okafor@greenleaf.vc',
        to: 'you@company.com',
        subject: 'CRM for our portfolio companies',
        body: "Hi,\n\nI'm a partner at GreenLeaf Ventures. We're looking for a CRM that our portfolio companies (12 startups) could use under a single managed account.\n\nDoes your platform support multi-tenant management from a central admin?\n\nJames Okafor",
        timestamp: '2026-02-15 03:00 PM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e5-2',
        from: 'you@company.com',
        to: 'james.okafor@greenleaf.vc',
        subject: 'Re: CRM for your portfolio companies',
        body: "Hi James,\n\nYes — our Enterprise plan is designed exactly for this. You get a master admin account with sub-organisation management, consolidated billing, and per-company analytics.\n\nI'd love to walk you through a demo. Would Thursday or Friday this week work?\n\nAlex",
        timestamp: '2026-02-15 04:30 PM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e5-3',
        from: 'james.okafor@greenleaf.vc',
        to: 'you@company.com',
        subject: 'Re: CRM for your portfolio companies',
        body: "Friday works. 11 AM? Also, please send a one-pager or slide deck beforehand — I'll share it with our ops team.\n\nJames",
        timestamp: '2026-02-16 09:00 AM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e5-4',
        from: 'you@company.com',
        to: 'james.okafor@greenleaf.vc',
        subject: 'Deck + Friday 11 AM confirmed',
        body: "Hi James,\n\nFriday 11 AM is confirmed — calendar invite attached. I've also included our Enterprise overview deck.\n\nSee you then!\nAlex",
        timestamp: '2026-02-16 11:00 AM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e5-5',
        from: 'james.okafor@greenleaf.vc',
        to: 'you@company.com',
        subject: 'Enterprise plan details',
        body: "Hi Alex,\n\nGood demo last week. I need a full feature breakdown for the Enterprise plan — specifically around user limits, API rate limits, and SLA guarantees. Our ops team wants to do a proper evaluation.\n\nCan you send that over?\n\nJames",
        timestamp: '2026-02-27 09:15 AM',
        direction: 'inbound',
        read: false,
      },
    ],
    sms: [
      {
        id: 's5-1',
        body: 'Hi James, Alex here. Just sent you the deck for Friday\'s demo. Let me know if you have any questions before then.',
        timestamp: '2026-02-16 11:05 AM',
        direction: 'outbound',
      },
      {
        id: 's5-2',
        body: 'Got it, thanks.',
        timestamp: '2026-02-16 11:22 AM',
        direction: 'inbound',
      },
      {
        id: 's5-3',
        body: 'Demo went well! Following up by email now with the Enterprise plan details.',
        timestamp: '2026-02-21 12:30 PM',
        direction: 'outbound',
      },
      {
        id: 's5-4',
        body: 'Great. I\'ll loop in our ops director next week.',
        timestamp: '2026-02-21 01:00 PM',
        direction: 'inbound',
      },
    ],
    calls: [
      {
        id: 'ca5-1',
        direction: 'inbound',
        duration: '45m 30s',
        outcome: 'answered',
        notes: 'Live demo for James + 2 ops team members. Covered multi-tenant admin, consolidated billing, and RBAC. Strong interest. James asked about white-labelling (not available) — flagged for product team.',
        timestamp: '2026-02-21 11:00 AM',
        hasRecording: true,
      },
    ],
    notes: [
      {
        id: 'n5-1',
        body: 'James represents a major opportunity — if we land GreenLeaf we get 12 portfolio companies on Enterprise. He is methodical and data-driven. Don\'t rush him.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-16 12:00 PM',
      },
      {
        id: 'n5-2',
        body: '@James flagged white-labelling request from this prospect. Worth a quick product discussion — if 12 companies are on board this could be a significant MRR driver.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-21 12:00 PM',
      },
      {
        id: 'n5-3',
        body: 'Follow-up task: send Enterprise plan feature matrix and SLA document. Deadline: by tomorrow EOD.',
        author: 'James Obi',
        authorInitials: 'JO',
        timestamp: '2026-02-27 09:30 AM',
      },
    ],
  },

  // ─── Elena Rossi · FinEdge Solutions ──────────────────────────────────────
  {
    thread: {
      id: 'c6',
      contactName: 'Elena Rossi',
      contactInitials: 'ER',
      avatarColor: 'bg-cyan-500',
      contactCompany: 'FinEdge Solutions',
      lastMessage: 'Waiting on budget approval from finance.',
      lastMessageTime: 'Feb 24',
      lastChannel: 'note',
      unreadCount: 0,
      status: 'pending',
    },
    emails: [
      {
        id: 'e6-1',
        from: 'elena.rossi@finedge.com',
        to: 'you@company.com',
        subject: 'CRM evaluation — financial services use case',
        body: "Hello,\n\nI manage sales operations at FinEdge Solutions, a fintech with 80 employees. We're evaluating CRMs with strong compliance and audit trail features.\n\nIs your platform GDPR compliant? Does it support custom audit logs?\n\nElena Rossi\nSales Operations Manager",
        timestamp: '2026-02-12 10:30 AM',
        direction: 'inbound',
        read: true,
      },
      {
        id: 'e6-2',
        from: 'you@company.com',
        to: 'elena.rossi@finedge.com',
        subject: 'Re: CRM evaluation — financial services use case',
        body: "Hi Elena,\n\nYes — we're fully GDPR and CCPA compliant. Our Enterprise plan includes detailed audit trails, role-based access control, and data residency options.\n\nI'd love to arrange a compliance-focused walkthrough. Are you available for a call next week?\n\nAlex",
        timestamp: '2026-02-12 02:00 PM',
        direction: 'outbound',
        read: true,
      },
      {
        id: 'e6-3',
        from: 'you@company.com',
        to: 'elena.rossi@finedge.com',
        subject: 'Following up — compliance demo',
        body: "Hi Elena,\n\nJust following up on my last email. We did a great walkthrough with your colleague last week and I wanted to make sure you had everything you needed for the evaluation.\n\nHappy to answer any questions from your compliance or legal team.\n\nAlex",
        timestamp: '2026-02-24 10:00 AM',
        direction: 'outbound',
        read: true,
      },
    ],
    sms: [
      {
        id: 's6-1',
        body: 'Hi Elena, Alex here. Did you get a chance to review the compliance docs I sent?',
        timestamp: '2026-02-22 11:00 AM',
        direction: 'outbound',
      },
      {
        id: 's6-2',
        body: 'Yes, they look good. We\'re waiting on budget sign-off from our finance director. Should have an answer by end of next week.',
        timestamp: '2026-02-22 11:30 AM',
        direction: 'inbound',
      },
    ],
    calls: [
      {
        id: 'ca6-1',
        direction: 'outbound',
        duration: '28m 45s',
        outcome: 'answered',
        notes: 'Compliance-focused demo. Elena brought in their legal counsel briefly. Covered GDPR consent management, audit logs, and data residency. Legal team was satisfied. Budget approval is the final hurdle.',
        timestamp: '2026-02-17 02:00 PM',
        hasRecording: true,
      },
      {
        id: 'ca6-2',
        direction: 'outbound',
        duration: '0m 0s',
        outcome: 'busy',
        notes: 'Called to check on budget status — line was busy. Will try again tomorrow.',
        timestamp: '2026-02-25 03:00 PM',
        hasRecording: false,
      },
    ],
    notes: [
      {
        id: 'n6-1',
        body: 'Elena is thorough and process-driven. The legal team has signed off on compliance. The only blocker now is finance approval — their budget cycle closes March 31. We need to close before then.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-17 03:00 PM',
      },
      {
        id: 'n6-2',
        body: 'Waiting on budget approval from finance. Elena confirmed decision by March 7 at the latest. @James put a follow-up task for March 6.',
        author: 'Alex Rivera',
        authorInitials: 'AR',
        timestamp: '2026-02-24 11:00 AM',
      },
    ],
  },
]
