import type { Opportunity, Stage, StageColor, ColorConfig, BoardConfig, Pipeline, SavedView } from './typings'

// ─── Legacy stage config (used by OpportunityList badges) ────────────────────

export interface StageConfig {
  label: string
  probability: number
  textColor: string
  bgColor: string
  cardBorderClass: string
  columnBgClass: string
  badgeClass: string
}

export const STAGE_CONFIG: Record<Stage, StageConfig> = {
  prospecting: {
    label: 'Prospecting',
    probability: 10,
    textColor: 'text-primary',
    bgColor: 'bg-[oklch(var(--metric-blue))]',
    cardBorderClass: 'border-l-4 border-l-primary',
    columnBgClass: 'bg-primary/5',
    badgeClass: 'bg-[oklch(var(--metric-blue))] text-primary border-primary/20',
  },
  qualification: {
    label: 'Qualification',
    probability: 25,
    textColor: 'text-[oklch(var(--warning))]',
    bgColor: 'bg-[oklch(var(--metric-orange))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--warning))]',
    columnBgClass: 'bg-[oklch(var(--warning))]/5',
    badgeClass: 'bg-[oklch(var(--metric-orange))] text-[oklch(var(--warning))] border-[oklch(var(--warning))]/20',
  },
  proposal: {
    label: 'Proposal',
    probability: 50,
    textColor: 'text-[oklch(var(--secondary))]',
    bgColor: 'bg-[oklch(var(--metric-purple))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--secondary))]',
    columnBgClass: 'bg-[oklch(var(--secondary))]/5',
    badgeClass: 'bg-[oklch(var(--metric-purple))] text-[oklch(var(--secondary))] border-[oklch(var(--secondary))]/20',
  },
  negotiation: {
    label: 'Negotiation',
    probability: 75,
    textColor: 'text-amber-600 dark:text-amber-400',
    bgColor: 'bg-amber-50 dark:bg-amber-950/40',
    cardBorderClass: 'border-l-4 border-l-amber-500',
    columnBgClass: 'bg-amber-500/5',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800',
  },
  'closed-won': {
    label: 'Closed Won',
    probability: 100,
    textColor: 'text-[oklch(var(--success))]',
    bgColor: 'bg-[oklch(var(--metric-green))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--success))]',
    columnBgClass: 'bg-[oklch(var(--success))]/5',
    badgeClass: 'bg-[oklch(var(--metric-green))] text-[oklch(var(--success))] border-[oklch(var(--success))]/20',
  },
  'closed-lost': {
    label: 'Closed Lost',
    probability: 0,
    textColor: 'text-destructive',
    bgColor: 'bg-[oklch(var(--metric-red))]',
    cardBorderClass: 'border-l-4 border-l-destructive',
    columnBgClass: 'bg-destructive/5',
    badgeClass: 'bg-[oklch(var(--metric-red))] text-destructive border-destructive/20',
  },
}

// ─── Color palette for board config ──────────────────────────────────────────

export const STAGE_COLORS: Record<StageColor, ColorConfig> = {
  blue: {
    dot: 'oklch(0.58 0.22 245)',
    textColor: 'text-primary',
    bgColor: 'bg-[oklch(var(--metric-blue))]',
    cardBorderClass: 'border-l-4 border-l-primary',
    columnBgClass: 'bg-primary/5',
    badgeClass: 'bg-[oklch(var(--metric-blue))] text-primary border-primary/20',
  },
  orange: {
    dot: 'oklch(0.7 0.2 60)',
    textColor: 'text-[oklch(var(--warning))]',
    bgColor: 'bg-[oklch(var(--metric-orange))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--warning))]',
    columnBgClass: 'bg-[oklch(var(--warning))]/5',
    badgeClass: 'bg-[oklch(var(--metric-orange))] text-[oklch(var(--warning))] border-[oklch(var(--warning))]/20',
  },
  purple: {
    dot: 'oklch(0.6 0.2 280)',
    textColor: 'text-[oklch(var(--secondary))]',
    bgColor: 'bg-[oklch(var(--metric-purple))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--secondary))]',
    columnBgClass: 'bg-[oklch(var(--secondary))]/5',
    badgeClass: 'bg-[oklch(var(--metric-purple))] text-[oklch(var(--secondary))] border-[oklch(var(--secondary))]/20',
  },
  green: {
    dot: 'oklch(0.65 0.18 150)',
    textColor: 'text-[oklch(var(--success))]',
    bgColor: 'bg-[oklch(var(--metric-green))]',
    cardBorderClass: 'border-l-4 border-l-[oklch(var(--success))]',
    columnBgClass: 'bg-[oklch(var(--success))]/5',
    badgeClass: 'bg-[oklch(var(--metric-green))] text-[oklch(var(--success))] border-[oklch(var(--success))]/20',
  },
  red: {
    dot: 'oklch(0.6 0.24 27)',
    textColor: 'text-destructive',
    bgColor: 'bg-[oklch(var(--metric-red))]',
    cardBorderClass: 'border-l-4 border-l-destructive',
    columnBgClass: 'bg-destructive/5',
    badgeClass: 'bg-[oklch(var(--metric-red))] text-destructive border-destructive/20',
  },
  amber: {
    dot: 'oklch(0.77 0.15 75)',
    textColor: 'text-amber-600 dark:text-amber-400',
    bgColor: 'bg-amber-50 dark:bg-amber-950/40',
    cardBorderClass: 'border-l-4 border-l-amber-500',
    columnBgClass: 'bg-amber-500/5',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800',
  },
  gray: {
    dot: 'oklch(0.55 0 0)',
    textColor: 'text-muted-foreground',
    bgColor: 'bg-muted',
    cardBorderClass: 'border-l-4 border-l-muted-foreground/40',
    columnBgClass: 'bg-muted/40',
    badgeClass: 'bg-muted text-muted-foreground border-border',
  },
}

export const PIPELINE_STAGES: Stage[] = [
  'prospecting',
  'qualification',
  'proposal',
  'negotiation',
  'closed-won',
  'closed-lost',
]

const DEFAULT_STAGE_COLORS: Record<Stage, StageColor> = {
  prospecting: 'blue',
  qualification: 'orange',
  proposal: 'purple',
  negotiation: 'amber',
  'closed-won': 'green',
  'closed-lost': 'red',
}

export const DEFAULT_BOARD_CONFIG: BoardConfig = {
  stages: PIPELINE_STAGES.map((stage) => ({
    stage,
    visible: true,
    label: STAGE_CONFIG[stage].label,
    color: DEFAULT_STAGE_COLORS[stage],
  })),
  cardFields: {
    value: true,
    probability: true,
    closeDate: true,
    assignee: true,
    company: true,
  },
  columnWidth: 272,
}

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  // Prospecting
  {
    id: '1',
    name: 'Enterprise CRM Migration',
    company: 'TechCorp Global',
    contact: 'Rachel Kim',
    value: 85000,
    stage: 'prospecting',
    probability: 10,
    expectedCloseDate: 'Apr 30, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2025-02-01',
  },
  {
    id: '2',
    name: 'Cloud Infrastructure Upgrade',
    company: 'DataSystems Inc',
    contact: 'Mark Lawson',
    value: 45000,
    stage: 'prospecting',
    probability: 15,
    expectedCloseDate: 'May 15, 2025',
    assignedTo: 'James R.',
    createdAt: '2025-02-05',
  },
  {
    id: '3',
    name: 'Marketing Automation Suite',
    company: 'Bright Media Co',
    contact: 'Laura Martinez',
    value: 32000,
    stage: 'prospecting',
    probability: 10,
    expectedCloseDate: 'May 20, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2025-02-10',
  },
  {
    id: '4',
    name: 'Security Audit & Implementation',
    company: 'SecureNet Corp',
    contact: 'Victor Huang',
    value: 28000,
    stage: 'prospecting',
    probability: 20,
    expectedCloseDate: 'Jun 1, 2025',
    assignedTo: 'James R.',
    createdAt: '2025-02-12',
  },
  // Qualification
  {
    id: '5',
    name: 'ERP System Integration',
    company: 'Meridian Group',
    contact: 'Carlos Herrera',
    value: 120000,
    stage: 'qualification',
    probability: 30,
    expectedCloseDate: 'Apr 15, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2025-01-20',
  },
  {
    id: '6',
    name: 'Customer Support Platform',
    company: 'RetailCo',
    contact: 'Robert Thompson',
    value: 55000,
    stage: 'qualification',
    probability: 25,
    expectedCloseDate: 'Apr 28, 2025',
    assignedTo: 'James R.',
    createdAt: '2025-01-25',
  },
  {
    id: '7',
    name: 'Data Analytics Dashboard',
    company: 'CloudPeak Systems',
    contact: 'Raj Nair',
    value: 40000,
    stage: 'qualification',
    probability: 35,
    expectedCloseDate: 'May 5, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2025-01-28',
  },
  // Proposal
  {
    id: '8',
    name: 'Sales Intelligence Platform',
    company: 'InnovaTech Solutions',
    contact: 'Alex Turner',
    value: 95000,
    stage: 'proposal',
    probability: 55,
    expectedCloseDate: 'Mar 31, 2025',
    assignedTo: 'James R.',
    notes: 'Proposal sent, awaiting feedback on pricing.',
    createdAt: '2025-01-10',
  },
  {
    id: '9',
    name: 'HR Management System',
    company: 'FinBridge Capital',
    contact: 'Aisha Kamara',
    value: 68000,
    stage: 'proposal',
    probability: 50,
    expectedCloseDate: 'Apr 10, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2025-01-15',
  },
  {
    id: '10',
    name: 'Supply Chain Optimization',
    company: 'BuildRight Construction',
    contact: 'Tom Anderson',
    value: 75000,
    stage: 'proposal',
    probability: 45,
    expectedCloseDate: 'Apr 20, 2025',
    assignedTo: 'James R.',
    createdAt: '2025-01-18',
  },
  // Negotiation
  {
    id: '11',
    name: 'AI-Powered CRM Suite',
    company: 'LuxeBrands',
    contact: 'Sophie Laurent',
    value: 180000,
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: 'Mar 20, 2025',
    assignedTo: 'Sarah K.',
    notes: 'Final pricing discussion scheduled for next week.',
    createdAt: '2024-12-15',
  },
  {
    id: '12',
    name: 'Omnichannel Communication',
    company: 'NexWave Technologies',
    contact: 'Priya Sharma',
    value: 62000,
    stage: 'negotiation',
    probability: 75,
    expectedCloseDate: 'Mar 25, 2025',
    assignedTo: 'James R.',
    createdAt: '2024-12-20',
  },
  // Closed Won
  {
    id: '13',
    name: 'Digital Transformation Program',
    company: 'Acme Corp',
    contact: 'Sarah Johnson',
    value: 240000,
    stage: 'closed-won',
    probability: 100,
    expectedCloseDate: 'Feb 28, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2024-11-01',
  },
  {
    id: '14',
    name: 'SaaS Integration Suite',
    company: 'HealthSpan AI',
    contact: 'Zoe Mitchell',
    value: 88000,
    stage: 'closed-won',
    probability: 100,
    expectedCloseDate: 'Feb 15, 2025',
    assignedTo: 'James R.',
    createdAt: '2024-11-10',
  },
  {
    id: '15',
    name: 'Business Intelligence Tool',
    company: 'UrbanTech',
    contact: 'Marcus Webb',
    value: 52000,
    stage: 'closed-won',
    probability: 100,
    expectedCloseDate: 'Jan 31, 2025',
    assignedTo: 'Sarah K.',
    createdAt: '2024-10-20',
  },
  // Closed Lost
  {
    id: '16',
    name: 'Legacy System Migration',
    company: 'AgriMax Corp',
    contact: 'Elena Vasquez',
    value: 95000,
    stage: 'closed-lost',
    probability: 0,
    expectedCloseDate: 'Feb 1, 2025',
    assignedTo: 'James R.',
    notes: 'Lost to competitor on pricing.',
    createdAt: '2024-10-15',
  },
  {
    id: '17',
    name: 'Customer Portal Development',
    company: 'SwiftLogix',
    contact: 'Nathan Brooks',
    value: 38000,
    stage: 'closed-lost',
    probability: 0,
    expectedCloseDate: 'Jan 20, 2025',
    assignedTo: 'Sarah K.',
    notes: 'Client decided to build in-house.',
    createdAt: '2024-10-25',
  },
]

export const MOCK_PIPELINES: Pipeline[] = [
  { id: '1', name: 'Sales Pipeline', description: 'Main B2B sales pipeline', dealCount: 12, totalValue: 980000, isDefault: true, createdAt: '2024-09-01' },
  { id: '2', name: 'Enterprise Deals', description: 'Large enterprise accounts only', dealCount: 4, totalValue: 560000, isDefault: false, createdAt: '2024-11-15' },
  { id: '3', name: 'Partnerships', description: 'Strategic partnership opportunities', dealCount: 3, totalValue: 180000, isDefault: false, createdAt: '2025-01-10' },
]

export const MOCK_SAVED_VIEWS: SavedView[] = [
  { id: '1', name: 'High Value Q1', filters: { assignees: [], minValue: '50000', maxValue: '', closeDateFrom: '2025-01-01', closeDateTo: '2025-03-31', minProbability: 0 } },
  { id: '2', name: 'My Deals', filters: { assignees: ['Sarah K.'], minValue: '', maxValue: '', closeDateFrom: '', closeDateTo: '', minProbability: 0 } },
]
