import { Contact, Company } from './typings'

export const MOCK_CONTACTS: Contact[] = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@acmecorp.com',
    phone: '+1 (555) 234-5678',
    company: 'Acme Corp',
    position: 'VP of Operations',
    status: 'active',
    tags: ['enterprise', 'decision-maker'],
    linkedin: 'linkedin.com/in/sarahjohnson',
    lastContacted: '2 days ago',
    createdAt: '2024-11-10',
  },
  {
    id: '2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'mchen@techstart.io',
    phone: '+1 (555) 345-6789',
    company: 'TechStart Inc',
    position: 'CEO',
    status: 'prospect',
    tags: ['startup', 'hot-lead'],
    lastContacted: '1 week ago',
    createdAt: '2024-12-01',
  },
  {
    id: '3',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.r@globalsys.com',
    phone: '+1 (555) 456-7890',
    company: 'Global Systems',
    position: 'IT Director',
    status: 'active',
    tags: ['enterprise', 'technical'],
    linkedin: 'linkedin.com/in/emilyrodriguez',
    twitter: '@emilyrod',
    lastContacted: 'Yesterday',
    createdAt: '2024-10-22',
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Kim',
    email: 'd.kim@nexusventures.com',
    phone: '+1 (555) 567-8901',
    company: 'Nexus Ventures',
    position: 'Partner',
    status: 'active',
    tags: ['investor', 'vip'],
    lastContacted: '3 days ago',
    createdAt: '2024-09-15',
  },
  {
    id: '5',
    firstName: 'Laura',
    lastName: 'Martinez',
    email: 'l.martinez@brightmedia.co',
    phone: '+1 (555) 678-9012',
    company: 'Bright Media',
    position: 'Marketing Manager',
    status: 'prospect',
    tags: ['smb', 'marketing'],
    lastContacted: '2 weeks ago',
    createdAt: '2025-01-05',
  },
  {
    id: '6',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'jwilson@alphafinance.com',
    phone: '+1 (555) 789-0123',
    company: 'Alpha Finance',
    position: 'CFO',
    status: 'inactive',
    tags: ['finance', 'enterprise'],
    lastContacted: '1 month ago',
    createdAt: '2024-08-20',
  },
  {
    id: '7',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya@cloudworks.ai',
    phone: '+1 (555) 890-1234',
    company: 'CloudWorks AI',
    position: 'CTO',
    status: 'active',
    tags: ['tech', 'ai', 'hot-lead'],
    linkedin: 'linkedin.com/in/priyapatel',
    lastContacted: 'Today',
    createdAt: '2025-01-20',
  },
  {
    id: '8',
    firstName: 'Robert',
    lastName: 'Thompson',
    email: 'rthompson@retailco.com',
    phone: '+1 (555) 901-2345',
    company: 'RetailCo',
    position: 'Head of Procurement',
    status: 'prospect',
    tags: ['retail', 'smb'],
    lastContacted: '5 days ago',
    createdAt: '2025-02-01',
  },
]

export const MOCK_COMPANIES: Company[] = [
  { id: '1', name: 'Acme Corp', industry: 'Manufacturing', size: '500-1000', website: 'acmecorp.com', contactCount: 4, createdAt: '2024-09-01' },
  { id: '2', name: 'TechStart Inc', industry: 'Technology', size: '10-50', website: 'techstart.io', contactCount: 2, createdAt: '2024-11-15' },
  { id: '3', name: 'Global Systems', industry: 'IT Services', size: '1000+', website: 'globalsys.com', contactCount: 6, createdAt: '2024-08-10' },
]

export const STATUS_OPTIONS = [
  { value: 'all', label: 'All Statuses' },
  { value: 'active', label: 'Active' },
  { value: 'prospect', label: 'Prospect' },
  { value: 'inactive', label: 'Inactive' },
]
