import type { CalendarEvent, EventType } from './typings'

export const EVENT_TYPE_COLORS: Record<EventType, string> = {
  task: 'bg-amber-500',
  call: 'bg-emerald-500',
  meeting: 'bg-primary',
  demo: 'bg-violet-500',
}

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: '1',
    title: 'Team Standup',
    type: 'meeting',
    date: '2026-03-02',
    startTime: '09:00',
    duration: 30,
    assignee: 'Sarah K.',
    description: 'Daily team sync to review progress and blockers.',
    color: 'bg-primary',
  },
  {
    id: '2',
    title: 'Demo with Acme Corp',
    type: 'demo',
    date: '2026-03-03',
    startTime: '14:00',
    duration: 60,
    linkedContact: 'Sarah Johnson',
    assignee: 'James R.',
    description: 'Product demo for the Digital Transformation deal.',
    color: 'bg-violet-500',
  },
  {
    id: '3',
    title: 'Follow-up Call – TechStart',
    type: 'call',
    date: '2026-03-04',
    startTime: '10:30',
    duration: 30,
    linkedContact: 'Michael Chen',
    assignee: 'Sarah K.',
    description: 'Discuss proposal feedback and next steps.',
    color: 'bg-emerald-500',
  },
  {
    id: '4',
    title: 'Prepare Q1 Report',
    type: 'task',
    date: '2026-03-05',
    startTime: '08:00',
    duration: 120,
    assignee: 'Sarah K.',
    description: 'Compile sales performance data for Q1 report.',
    color: 'bg-amber-500',
  },
  {
    id: '5',
    title: 'Kickoff – CloudWorks AI',
    type: 'meeting',
    date: '2026-03-05',
    startTime: '14:00',
    duration: 60,
    linkedContact: 'Priya Patel',
    assignee: 'James R.',
    description: 'Project kickoff meeting with CloudWorks AI team.',
    color: 'bg-primary',
  },
  {
    id: '6',
    title: 'HealthSpan Deal Review',
    type: 'meeting',
    date: '2026-03-09',
    startTime: '11:00',
    duration: 45,
    linkedContact: 'Zoe Mitchell',
    assignee: 'James R.',
    description: 'Review deal status and next steps.',
    color: 'bg-primary',
  },
  {
    id: '7',
    title: 'Discovery Call – EduFirst',
    type: 'call',
    date: '2026-03-10',
    startTime: '15:00',
    duration: 30,
    assignee: 'James R.',
    description: 'Initial discovery call with EduFirst Academy.',
    color: 'bg-emerald-500',
  },
  {
    id: '8',
    title: 'Global Systems Demo',
    type: 'demo',
    date: '2026-03-11',
    startTime: '10:00',
    duration: 90,
    linkedContact: 'Emily Rodriguez',
    assignee: 'Sarah K.',
    description: 'Full platform demo for Global Systems IT team.',
    color: 'bg-violet-500',
  },
  {
    id: '9',
    title: 'Update CRM Records',
    type: 'task',
    date: '2026-03-12',
    startTime: '09:00',
    duration: 60,
    assignee: 'Sarah K.',
    description: 'Clean up and update contact and deal records.',
    color: 'bg-amber-500',
  },
  {
    id: '10',
    title: 'Weekly Sales Review',
    type: 'meeting',
    date: '2026-03-13',
    startTime: '13:00',
    duration: 60,
    assignee: 'Sarah K.',
    description: 'Weekly team sales review and pipeline discussion.',
    color: 'bg-primary',
  },
  {
    id: '11',
    title: 'Call – Alpha Finance',
    type: 'call',
    date: '2026-03-16',
    startTime: '10:00',
    duration: 30,
    linkedContact: 'James Wilson',
    assignee: 'James R.',
    description: 'Re-engagement call with Alpha Finance CFO.',
    color: 'bg-emerald-500',
  },
  {
    id: '12',
    title: 'Proposal Review – RetailCo',
    type: 'meeting',
    date: '2026-03-17',
    startTime: '15:30',
    duration: 45,
    linkedContact: 'Robert Thompson',
    assignee: 'Sarah K.',
    description: 'Internal review of the RetailCo proposal before sending.',
    color: 'bg-primary',
  },
  {
    id: '13',
    title: 'Send Contracts',
    type: 'task',
    date: '2026-03-18',
    startTime: '09:00',
    duration: 30,
    assignee: 'James R.',
    description: 'Send finalized contracts to closed-won clients.',
    color: 'bg-amber-500',
  },
  {
    id: '14',
    title: 'Product Demo – Bright Media',
    type: 'demo',
    date: '2026-03-20',
    startTime: '11:00',
    duration: 60,
    linkedContact: 'Laura Martinez',
    assignee: 'Sarah K.',
    description: 'Marketing automation demo for Bright Media.',
    color: 'bg-violet-500',
  },
  {
    id: '15',
    title: 'End of Month Pipeline Review',
    type: 'meeting',
    date: '2026-03-30',
    startTime: '14:00',
    duration: 90,
    assignee: 'Sarah K.',
    description: 'Full pipeline review and forecast for April.',
    color: 'bg-primary',
  },
]
