import type { Lead } from './typings'

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    firstName: 'Alex',
    lastName: 'Turner',
    email: 'alex.turner@innovatech.com',
    phone: '+1 (555) 101-2020',
    company: 'InnovaTech Solutions',
    position: 'CTO',
    status: 'qualified',
    source: 'referral',
    score: 87,
    value: 45000,
    assignedTo: 'Sarah K.',
    lastActivity: '1 day ago',
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    firstName: 'Maya',
    lastName: 'Patel',
    email: 'm.patel@dataflow.io',
    phone: '+1 (555) 202-3131',
    company: 'DataFlow Inc',
    position: 'Head of Engineering',
    status: 'new',
    source: 'website',
    score: 62,
    value: 28000,
    lastActivity: 'Today',
    createdAt: '2025-02-10',
  },
  {
    id: '3',
    firstName: 'Carlos',
    lastName: 'Herrera',
    email: 'c.herrera@meridian.co',
    phone: '+1 (555) 303-4242',
    company: 'Meridian Group',
    position: 'VP of Sales',
    status: 'contacted',
    source: 'event',
    score: 74,
    value: 62000,
    assignedTo: 'James R.',
    lastActivity: '3 days ago',
    createdAt: '2025-01-22',
  },
  {
    id: '4',
    firstName: 'Sophie',
    lastName: 'Laurent',
    email: 'sophie.l@luxebrands.com',
    phone: '+1 (555) 404-5353',
    company: 'LuxeBrands',
    position: 'CMO',
    status: 'qualified',
    source: 'social',
    score: 91,
    value: 120000,
    assignedTo: 'Sarah K.',
    lastActivity: 'Yesterday',
    createdAt: '2025-01-08',
  },
  {
    id: '5',
    firstName: 'Tom',
    lastName: 'Anderson',
    email: 'tom.a@buildright.com',
    phone: '+1 (555) 505-6464',
    company: 'BuildRight Construction',
    position: 'Procurement Manager',
    status: 'unqualified',
    source: 'phone',
    score: 28,
    value: 8000,
    lastActivity: '2 weeks ago',
    createdAt: '2024-12-18',
  },
  {
    id: '6',
    firstName: 'Aisha',
    lastName: 'Kamara',
    email: 'aisha@finbridge.com',
    phone: '+1 (555) 606-7575',
    company: 'FinBridge Capital',
    position: 'Director of Partnerships',
    status: 'converted',
    source: 'referral',
    score: 96,
    value: 200000,
    assignedTo: 'James R.',
    lastActivity: '5 days ago',
    createdAt: '2024-11-30',
  },
  {
    id: '7',
    firstName: 'Nathan',
    lastName: 'Brooks',
    email: 'n.brooks@swiftlogix.com',
    phone: '+1 (555) 707-8686',
    company: 'SwiftLogix',
    position: 'COO',
    status: 'new',
    source: 'email',
    score: 55,
    value: 35000,
    lastActivity: 'Today',
    createdAt: '2025-02-15',
  },
  {
    id: '8',
    firstName: 'Zoe',
    lastName: 'Mitchell',
    email: 'zoe.m@healthspan.ai',
    phone: '+1 (555) 808-9797',
    company: 'HealthSpan AI',
    position: 'CEO',
    status: 'contacted',
    source: 'website',
    score: 79,
    value: 88000,
    assignedTo: 'Sarah K.',
    lastActivity: '2 days ago',
    createdAt: '2025-01-28',
  },
  {
    id: '9',
    firstName: 'Raj',
    lastName: 'Nair',
    email: 'raj.nair@cloudpeak.io',
    phone: '+1 (555) 909-0808',
    company: 'CloudPeak Systems',
    position: 'SVP Technology',
    status: 'qualified',
    source: 'event',
    score: 83,
    value: 72000,
    assignedTo: 'James R.',
    lastActivity: '1 day ago',
    createdAt: '2025-01-12',
  },
  {
    id: '10',
    firstName: 'Elena',
    lastName: 'Vasquez',
    email: 'e.vasquez@agrimax.com',
    phone: '+1 (555) 010-1919',
    company: 'AgriMax Corp',
    position: 'Head of Operations',
    status: 'unqualified',
    source: 'other',
    score: 34,
    value: 12000,
    lastActivity: '1 month ago',
    createdAt: '2024-12-05',
  },
  {
    id: '11',
    firstName: 'Marcus',
    lastName: 'Webb',
    email: 'm.webb@urbantech.io',
    phone: '+1 (555) 111-2020',
    company: 'UrbanTech',
    position: 'Product Director',
    status: 'converted',
    source: 'social',
    score: 94,
    value: 155000,
    assignedTo: 'Sarah K.',
    lastActivity: '1 week ago',
    createdAt: '2024-11-15',
  },
  {
    id: '12',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'p.sharma@nexwave.in',
    phone: '+1 (555) 122-3131',
    company: 'NexWave Technologies',
    position: 'Business Development',
    status: 'new',
    source: 'referral',
    score: 67,
    value: 42000,
    lastActivity: 'Today',
    createdAt: '2025-02-20',
  },
]

export const LEAD_STATUS_OPTIONS = [
  { value: 'all', label: 'All Statuses' },
  { value: 'new', label: 'New' },
  { value: 'contacted', label: 'Contacted' },
  { value: 'qualified', label: 'Qualified' },
  { value: 'unqualified', label: 'Unqualified' },
  { value: 'converted', label: 'Converted' },
  { value: 'lost', label: 'Lost' },
]

export const LEAD_SOURCE_OPTIONS = [
  { value: 'all', label: 'All Sources' },
  { value: 'website', label: 'Website' },
  { value: 'referral', label: 'Referral' },
  { value: 'social', label: 'Social Media' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'event', label: 'Event' },
  { value: 'other', label: 'Other' },
]
