import type { Task, TaskPriority, TaskStatus, TaskCategory } from './typings'

export const TASK_PRIORITY_OPTIONS: { value: TaskPriority | 'all'; label: string }[] = [
  { value: 'all', label: 'All Priorities' },
  { value: 'low', label: 'Low' },
  { value: 'medium', label: 'Medium' },
  { value: 'high', label: 'High' },
  { value: 'urgent', label: 'Urgent' },
]

export const TASK_STATUS_OPTIONS: { value: TaskStatus | 'all'; label: string }[] = [
  { value: 'all', label: 'All Statuses' },
  { value: 'todo', label: 'To Do' },
  { value: 'in-progress', label: 'In Progress' },
  { value: 'completed', label: 'Completed' },
  { value: 'cancelled', label: 'Cancelled' },
]

export const TASK_CATEGORY_OPTIONS: { value: TaskCategory | 'all'; label: string }[] = [
  { value: 'all', label: 'All Categories' },
  { value: 'call', label: 'Call' },
  { value: 'email', label: 'Email' },
  { value: 'meeting', label: 'Meeting' },
  { value: 'follow-up', label: 'Follow-up' },
  { value: 'demo', label: 'Demo' },
  { value: 'proposal', label: 'Proposal' },
  { value: 'other', label: 'Other' },
]

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    title: 'Follow up with Sarah Johnson on Digital Transformation proposal',
    description: 'Discuss pricing concerns raised during last call and share revised deck.',
    priority: 'urgent',
    status: 'todo',
    category: 'follow-up',
    dueDate: 'Feb 27, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '13', name: 'Digital Transformation Program' },
    createdAt: 'Feb 20, 2026',
  },
  {
    id: '2',
    title: 'Schedule discovery call with NexWave Technologies',
    description: 'Understand their omnichannel requirements before the next negotiation round.',
    priority: 'high',
    status: 'todo',
    category: 'call',
    dueDate: 'Feb 28, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '12', name: 'Omnichannel Communication' },
    createdAt: 'Feb 21, 2026',
  },
  {
    id: '3',
    title: 'Send proposal to BuildRight Construction',
    description: 'Include supply chain optimization ROI analysis and case studies.',
    priority: 'high',
    status: 'in-progress',
    category: 'proposal',
    dueDate: 'Mar 1, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '10', name: 'Supply Chain Optimization' },
    createdAt: 'Feb 18, 2026',
  },
  {
    id: '4',
    title: 'Demo ERP integration for Meridian Group',
    description: 'Live walk-through of the integration connectors. Invite Carlos and their IT lead.',
    priority: 'urgent',
    status: 'todo',
    category: 'demo',
    dueDate: 'Feb 26, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '5', name: 'ERP System Integration' },
    createdAt: 'Feb 15, 2026',
  },
  {
    id: '5',
    title: 'Qualify inbound lead from TechStart Inc',
    description: 'Review the lead form submission and reach out to assess fit.',
    priority: 'medium',
    status: 'todo',
    category: 'call',
    dueDate: 'Mar 3, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'lead', id: 'L1', name: 'Michael Torres' },
    createdAt: 'Feb 22, 2026',
  },
  {
    id: '6',
    title: 'Prepare Q1 pipeline review presentation',
    description: 'Summarize won/lost deals, forecasted revenue, and conversion rates.',
    priority: 'high',
    status: 'in-progress',
    category: 'other',
    dueDate: 'Mar 5, 2026',
    assignedTo: 'James R.',
    createdAt: 'Feb 20, 2026',
  },
  {
    id: '7',
    title: 'Send contract to LuxeBrands for AI-Powered CRM Suite',
    description: 'Final contract with updated SLA terms agreed in last meeting.',
    priority: 'urgent',
    status: 'todo',
    category: 'email',
    dueDate: 'Feb 25, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '11', name: 'AI-Powered CRM Suite' },
    createdAt: 'Feb 19, 2026',
  },
  {
    id: '8',
    title: 'Update contact record for Rachel Kim',
    description: 'Add new phone number and correct job title to Prospect.',
    priority: 'low',
    status: 'todo',
    category: 'other',
    dueDate: 'Mar 10, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'contact', id: 'C1', name: 'Rachel Kim' },
    createdAt: 'Feb 23, 2026',
  },
  {
    id: '9',
    title: 'Kick-off meeting with HealthSpan AI',
    description: 'Introduction call to align on project milestones and team contacts.',
    priority: 'medium',
    status: 'completed',
    category: 'meeting',
    dueDate: 'Feb 15, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '14', name: 'SaaS Integration Suite' },
    createdAt: 'Feb 10, 2026',
  },
  {
    id: '10',
    title: 'Review inbound email from CloudPeak Systems',
    description: 'They asked for a custom analytics module — check feasibility with product.',
    priority: 'medium',
    status: 'completed',
    category: 'email',
    dueDate: 'Feb 18, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '7', name: 'Data Analytics Dashboard' },
    createdAt: 'Feb 12, 2026',
  },
  {
    id: '11',
    title: 'Create onboarding checklist for Acme Corp',
    description: 'Tailor the standard onboarding template to their specific integration setup.',
    priority: 'medium',
    status: 'in-progress',
    category: 'other',
    dueDate: 'Mar 8, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '13', name: 'Digital Transformation Program' },
    createdAt: 'Feb 21, 2026',
  },
  {
    id: '12',
    title: 'Log call notes from RetailCo discovery session',
    priority: 'low',
    status: 'todo',
    category: 'follow-up',
    dueDate: 'Mar 2, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '6', name: 'Customer Support Platform' },
    createdAt: 'Feb 22, 2026',
  },
  {
    id: '13',
    title: 'LinkedIn outreach to Aisha Kamara — HR integration case study',
    description: 'Share the FinBridge case study and ask for a 15-minute intro call.',
    priority: 'medium',
    status: 'todo',
    category: 'email',
    dueDate: 'Mar 4, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'contact', id: 'C9', name: 'Aisha Kamara' },
    createdAt: 'Feb 23, 2026',
  },
  {
    id: '14',
    title: 'Product demo for InnovaTech Solutions',
    description: 'Demo the sales intelligence module with live data integration.',
    priority: 'high',
    status: 'completed',
    category: 'demo',
    dueDate: 'Feb 20, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '8', name: 'Sales Intelligence Platform' },
    createdAt: 'Feb 14, 2026',
  },
  {
    id: '15',
    title: 'Call Priya Sharma to confirm negotiation meeting',
    priority: 'high',
    status: 'todo',
    category: 'call',
    dueDate: 'Feb 27, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '12', name: 'Omnichannel Communication' },
    createdAt: 'Feb 22, 2026',
  },
  {
    id: '16',
    title: 'Archive lost deal records for AgriMax Corp',
    description: 'Tag records with "competitor-pricing" loss reason and move to archive.',
    priority: 'low',
    status: 'cancelled',
    category: 'other',
    dueDate: 'Feb 10, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '16', name: 'Legacy System Migration' },
    createdAt: 'Feb 5, 2026',
  },
  {
    id: '17',
    title: 'Send welcome email to UrbanTech team',
    description: 'Welcome the UrbanTech team and share the customer success portal link.',
    priority: 'medium',
    status: 'completed',
    category: 'email',
    dueDate: 'Feb 3, 2026',
    assignedTo: 'James R.',
    relatedTo: { type: 'deal', id: '15', name: 'Business Intelligence Tool' },
    createdAt: 'Feb 1, 2026',
  },
  {
    id: '18',
    title: 'Prepare security audit proposal for SecureNet Corp',
    description: 'Include compliance checklist, timeline, and implementation team structure.',
    priority: 'high',
    status: 'in-progress',
    category: 'proposal',
    dueDate: 'Mar 6, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '4', name: 'Security Audit & Implementation' },
    createdAt: 'Feb 20, 2026',
  },
  {
    id: '19',
    title: 'Sync with marketing on Q1 campaign leads',
    description: 'Review which campaign leads are ready for sales handoff.',
    priority: 'medium',
    status: 'todo',
    category: 'meeting',
    dueDate: 'Mar 7, 2026',
    assignedTo: 'James R.',
    createdAt: 'Feb 22, 2026',
  },
  {
    id: '20',
    title: 'Confirm close date with Sophie Laurent (LuxeBrands)',
    description: 'Final check-in to confirm the Q1 close is still on track.',
    priority: 'urgent',
    status: 'in-progress',
    category: 'call',
    dueDate: 'Feb 26, 2026',
    assignedTo: 'Sarah K.',
    relatedTo: { type: 'deal', id: '11', name: 'AI-Powered CRM Suite' },
    createdAt: 'Feb 21, 2026',
  },
]
