import type { Company } from './typings'

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: 'Acme Corp',
    industry: 'Manufacturing',
    website: 'acmecorp.com',
    employees: 750,
    annualRevenue: 45000000,
    contactCount: 4,
    openDeals: 2,
    status: 'active',
    owner: 'Sarah K.',
    createdAt: '2024-09-01',
  },
  {
    id: '2',
    name: 'TechStart Inc',
    industry: 'Technology',
    website: 'techstart.io',
    employees: 32,
    annualRevenue: 2800000,
    contactCount: 2,
    openDeals: 1,
    status: 'active',
    owner: 'James R.',
    createdAt: '2024-11-15',
  },
  {
    id: '3',
    name: 'Global Systems',
    industry: 'IT Services',
    website: 'globalsys.com',
    employees: 1200,
    annualRevenue: 95000000,
    contactCount: 6,
    openDeals: 3,
    status: 'active',
    owner: 'Sarah K.',
    createdAt: '2024-08-10',
  },
  {
    id: '4',
    name: 'Alpha Finance',
    industry: 'Finance',
    website: 'alphafinance.com',
    employees: 430,
    annualRevenue: 62000000,
    contactCount: 3,
    openDeals: 1,
    status: 'inactive',
    owner: 'James R.',
    createdAt: '2024-08-20',
  },
  {
    id: '5',
    name: 'Bright Media',
    industry: 'Media',
    website: 'brightmedia.co',
    employees: 88,
    annualRevenue: 7500000,
    contactCount: 2,
    openDeals: 1,
    status: 'prospect',
    owner: 'Sarah K.',
    createdAt: '2025-01-05',
  },
  {
    id: '6',
    name: 'HealthSpan AI',
    industry: 'Healthcare',
    website: 'healthspan.ai',
    employees: 220,
    annualRevenue: 31000000,
    contactCount: 3,
    openDeals: 2,
    status: 'active',
    owner: 'James R.',
    createdAt: '2024-10-12',
  },
  {
    id: '7',
    name: 'RetailCo',
    industry: 'Retail',
    website: 'retailco.com',
    employees: 560,
    annualRevenue: 48000000,
    contactCount: 2,
    openDeals: 1,
    status: 'active',
    owner: 'Sarah K.',
    createdAt: '2025-02-01',
  },
  {
    id: '8',
    name: 'EduFirst Academy',
    industry: 'Education',
    website: 'edufirst.edu',
    employees: 145,
    annualRevenue: 9200000,
    contactCount: 1,
    openDeals: 0,
    status: 'prospect',
    owner: 'James R.',
    createdAt: '2025-01-20',
  },
  {
    id: '9',
    name: 'CloudWorks AI',
    industry: 'Technology',
    website: 'cloudworks.ai',
    employees: 65,
    annualRevenue: 5400000,
    contactCount: 2,
    openDeals: 2,
    status: 'active',
    owner: 'Sarah K.',
    createdAt: '2025-01-20',
  },
  {
    id: '10',
    name: 'Nexus Ventures',
    industry: 'Finance',
    website: 'nexusventures.com',
    employees: 38,
    annualRevenue: 125000000,
    contactCount: 1,
    openDeals: 0,
    status: 'inactive',
    owner: 'James R.',
    createdAt: '2024-09-15',
  },
]

export const INDUSTRY_OPTIONS = [
  { value: 'all', label: 'All Industries' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Education', label: 'Education' },
  { value: 'IT Services', label: 'IT Services' },
  { value: 'Media', label: 'Media' },
]

export const STATUS_OPTIONS = [
  { value: 'all', label: 'All Statuses' },
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'prospect', label: 'Prospect' },
]
